name: unit-tests
on: 
  push:
    branches:
    - master
  pull_request: 
    branches:
    - master
jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/viniciusbds/navio
    
    - name: Run all tests
      run: | 
        sudo make unit-tests
